### ISSUE TITLE
Deprecated selector in `darcula-syntax\index.less`

### ISSUE THREAD

**Issue by v2pwww** [VitaliyR/darcula-syntax#1]
In `darcula-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor .line.cursor-line,atom-text-editor .line.cursor-line`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor .line.cursor-line,
atom-text-editor::shadow .line.cursor-line,
:host .line.cursor-line,
atom-text-editor .selection .region,
atom-text-editor::shadow .selection .region,
:host .selection .region` => `atom-text-editor .line.cursor-line,
atom-text-editor.editor .line.cursor-line,atom-text-editor .line.cursor-line,
atom-text-editor .selection .region,
atom-text-editor.editor .selection .region,atom-text-editor .selection .region`

* `.regexp` => `.syntax--regexp`

* `.keyword` => `.syntax--keyword`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.operator` => `.syntax--keyword.syn

**Comment by VitaliyR** [comment]
@v2pwww got it, will update the package soon, thanks for notifying me.

**Comment by gevezex** [comment]
Any update on this issue?

**Comment by VitaliyR** [comment]
@gevezex sorry, this was fixed in 0.2.0.
